version: "3.7"
services:
  server:
    image: scrape-server:latest
    container_name: "artifact-scrape-backend"
    command: yarn debug
    volumes:
      - ./dist:/server/dist
    ports:
      - "3001:3001"
      - "9229:9229"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.2
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles
volumes:
  mongodata:
